"""Added new coloumn to patient table

Revision ID: 39424959b65f
Revises: 21119bc9fe0f
Create Date: 2025-12-07 11:58:37.729656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39424959b65f'
down_revision = '21119bc9fe0f'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'password_hash',
                sa.String(length=255),
                nullable=False,
                server_default=''
            )
        )



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
