"""added disease_type to report removed from image

Revision ID: ce0224916ec6
Revises: e2f32f2d3edb
Create Date: 2025-12-10 22:34:45.986830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce0224916ec6'
down_revision = 'e2f32f2d3edb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_column('disease_type')

    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disease_type', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_column('disease_type')

    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disease_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
